#!/bin/bash

#Compilar Programas

cd ./cpu/src/
gcc -w cpu.c -o cpu -lcommons -lpthread -lparser-ansisop
echo 'CPU Compilada'
echo ' '

cd ../../kernel/src/
gcc -w kernel.c -o kernel -lcommons -lpthread -lparser-ansisop
echo 'Kernel Compilado' 
echo ' '

cd ../../Programa/src
gcc -w Programa.c -o Programa -lcommons
echo 'Programa Compilado. Declarar variable de entorno!'
echo 'export ANSISOP_CONFIG=./config'
echo ' '

cd ../../umv/src
gcc -w umv.c -o umv -lcommons -lpthread
echo 'UMV Compilado'